name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: jryahia
          outputs: |
            "dist/github-contribution-grid-snake-dark.svg?color_snake=#f97316&color_dots=#0a0a0b,#161b22,#30363d,#f97316,#fdba74"

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
